#line 2 "1505063.cpp"

#line 4 "1505063.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[242] =
    {   0,
        0,    0,    2,    2,   75,   73,    7,    6,   65,   73,
       64,   60,   73,   39,   40,   49,   45,   50,   73,   64,
       66,   46,   51,   59,   53,   71,   71,   43,   44,   73,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       41,   63,   42,    2,    4,    3,   31,    7,   56,    0,
        0,   67,   31,    0,   57,   38,   31,   38,   38,   47,
       48,   32,   31,    1,    9,    0,   31,   33,   33,   61,
       52,   55,   54,   62,   31,   71,   71,    0,   27,   31,
       31,   72,   71,   71,   71,   71,   71,   15,   71,   71,
       71,   11,   71,   71,   71,   71,   71,   58,    2,    3,

        3,    5,    0,   70,   67,    0,    0,   70,    0,    0,
       70,    0,    0,   31,    0,    0,    0,   34,   31,    0,
        0,    0,   32,    0,    0,    0,    9,    9,   28,   30,
        0,   27,   71,   71,   71,   71,   71,   71,   71,   71,
       13,   17,   71,   71,   71,   71,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       68,    0,   69,   68,   35,   36,   37,   10,    8,    0,
       71,   24,   18,   71,   71,   71,   12,   71,   71,   71,
       21,   71,    0,    0,    0,    0,    0,   70,   68,    0,
       69,   68,    0,   68,   70,    0,    0,   69,   70,    0,

       69,    0,   68,    0,   69,    8,    8,    0,   29,   16,
       71,   71,   71,   19,   71,   71,   14,    0,    0,   68,
       69,   69,    0,    0,    0,   69,    0,    0,   68,    0,
       71,   71,   20,   22,   23,    0,    0,   71,   25,   26,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       24,   25,   26,    1,   27,    1,   28,   29,   30,   31,

       32,   33,   22,   34,   35,   22,   36,   37,   22,   38,
       39,   22,   22,   40,   41,   42,   43,   44,   45,   22,
       22,   22,   46,   47,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        5,    1,    1,    1,    6,    1,    7,    1,    1,    1,
        1,    7,    7,    1,    8,    1,    9,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[282] =
    {   0,
        0,    0,   46,   47,  656,  613,   49,  905,   35,   51,
      594,   46,   76,  588,  585,   47,  582,   48,   52,  114,
       56,  579,   55,  109,  115,   43,  125,  576,  554,  553,
      111,  116,  129,  130,  132,  137,  131,  145,  149,  157,
      552,  136,  551,    0,  905,  149,  550,  563,  905,  174,
      170,  175,  184,  189,  905,  905,  185,  554,  173,  905,
      905,  542,  181,  194,  533,  189,  193,  202,  206,  905,
      905,  905,  905,  905,  539,  186,    0,  207,    0,  210,
      538,    0,  209,  211,  212,  215,  216,  217,  218,  229,
      230,  231,  234,  237,  238,  245,  250,  905,    0,  196,

      255,  905,  278,  279,  513,  283,  509,  505,    0,  266,
      271,  489,  272,  284,  287,  290,  295,  905,  294,  475,
      474,  466,  394,  296,  302,  303,  342,  291,  306,  307,
      310,    0,  309,  301,  313,  314,  315,  317,  318,  321,
      330,  334,  335,  337,  338,  343,  314,  355,    0,  356,
      363,  368,  369,  372,  305,  275,  379,    0,  360,  384,
      387,  393,  396,  397,  905,  905,  905,  380,  238,  391,
      359,  389,  390,  392,  393,  396,  397,  398,  411,  412,
      414,  417,  427,  432,  423,  440,  443,  450,  225,  451,
      455,  444,  456,  905,  905,  447,  459,  234,  226,  461,

      468,  474,  227,  460,  464,  161,  467,  168,  165,  461,
      470,  473,  474,  477,  478,  485,  486,  493,  140,  138,
      131,  504,  512,  515,  518,  124,   58,  519,  522,  523,
      514,  518,  515,  519,  522,  547,  508,  534,  536,  537,
      905,  572,  581,  585,  588,  591,  600,  609,  618,  627,
      636,  645,  651,  658,  667,  670,  679,  688,  697,  706,
      715,  724,  733,  742,  751,  760,  769,  778,  787,  796,
      805,  814,  823,  832,  841,  850,  859,  868,  877,  886,
      895
    } ;

static yyconst flex_int16_t yy_def[282] =
    {   0,
      241,    1,  242,  242,  241,  241,  241,  241,  241,  243,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      244,  241,  241,  241,  241,  245,  245,  241,  241,  246,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      241,  241,  241,  247,  241,  248,  241,  241,  241,  249,
      250,  251,  249,  252,  241,  241,  253,  253,  241,  241,
      241,  241,  241,  254,  255,  241,  244,  244,  244,  241,
      241,  241,  241,  241,  256,  245,  256,  241,  257,  256,
      246,  246,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  241,  247,  248,

      248,  241,  243,  258,  259,  260,  250,  250,  261,  262,
      263,  259,  262,  243,  260,  264,  260,  241,  253,  253,
      241,  241,  241,  254,  254,  254,  255,  255,  241,  241,
      241,  257,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  265,  266,  267,  259,
      252,  268,  251,  252,  261,  241,  251,  266,  269,  261,
      251,  270,  271,  272,  241,  241,  241,  254,  273,  241,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  258,  274,  263,  274,  269,  274,  259,  268,
      271,  269,  275,  241,  241,  276,  269,  277,  261,  264,

      278,  271,  277,  276,  279,  273,  273,  241,  241,  245,
      245,  245,  245,  245,  245,  245,  245,  267,  267,  266,
      277,  271,  275,  268,  272,  277,  277,  280,  281,  281,
      245,  245,  245,  245,  245,  278,  279,  245,  245,  245,
        0,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241
    } ;

static yyconst flex_uint16_t yy_nxt[954] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       11,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,    6,   29,   30,   26,   31,   32,
       33,   34,   35,   26,   36,   26,   26,   26,   26,   37,
       38,   26,   26,   39,   40,   41,   42,   43,   45,   45,
       48,   47,   55,   51,   49,   52,   46,   46,   60,   75,
      221,   61,   47,   47,   47,   47,   62,   53,   63,   77,
       66,   47,   67,   70,   71,   54,   56,   56,   69,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   57,   56,   56,   56,   56,   58,   58,   56,

       59,   56,   56,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   56,   56,   56,   64,   47,  198,   75,   72,   65,
       47,   47,   75,  221,   73,   74,   78,   77,   78,   79,
      111,   80,   77,   84,  194,   75,   75,   75,   75,   85,
       83,   77,   47,   75,   86,   77,   77,   77,   77,  101,
       87,   75,   94,   77,  102,   75,   89,   88,   90,   92,
       91,   77,  108,   75,   93,   77,  104,  111,  105,  112,
       56,  209,   98,   77,  209,  207,  104,   96,  105,   95,
       97,  116,  118,  112,  109,   62,  125,   63,  106,  113,

      114,  119,   77,   62,  126,  129,  241,   66,  106,   67,
      121,  241,   77,  117,  122,   69,  241,   78,  241,   78,
       79,   79,  130,  131,   79,   77,   80,   77,   77,  221,
      194,   77,   77,   77,   77,   77,  221,   77,   77,  135,
      133,   77,   77,   77,   77,   77,   77,   77,  137,  150,
       77,  134,  136,   77,   77,   77,   77,   77,  139,  138,
       77,   77,  207,   77,   77,  101,   77,  140,  156,  141,
      102,   77,  144,  156,  159,  142,   77,  195,  143,  145,
       51,   51,   52,  148,  146,  152,   51,  153,   52,  160,
      157,  161,  163,  169,  164,  158,  157,  152,  125,  161,

       53,  165,   54,  149,  125,  125,  126,  154,   54,  194,
      119,  154,  126,  126,  154,  128,  104,   77,  168,  154,
       62,   79,  129,  130,   79,   77,  131,   77,  170,   77,
       77,   77,  172,   77,   77,   77,  171,   77,  184,   77,
       77,   77,  175,   77,   77,  176,   77,   77,  178,  177,
       77,   77,  173,   77,   77,  174,   77,  111,  187,   77,
       77,   77,  198,   77,   77,  188,  128,  189,  181,   77,
      191,  111,  192,  112,  116,   77,  189,  179,  180,  182,
      150,  196,  125,  112,  150,   77,  199,  117,  194,  111,
      126,  112,  193,  113,  210,  201,  117,  192,  191,  205,

      203,  197,  208,  113,  208,   77,   77,  209,   77,   77,
      123,  113,   77,   77,   77,   77,   77,  117,   77,   77,
      155,  113,   77,   77,   77,  156,  211,   77,   77,   51,
       77,  148,  213,   77,  160,  212,  148,   77,   77,  214,
       77,  216,  160,   77,  220,  221,  221,  158,  217,  226,
      215,  149,  160,  222,  220,  192,  219,  222,  224,  203,
      189,  221,  226,  163,  219,  164,  226,  150,  150,  169,
      163,  157,  229,  167,  219,  193,  222,   77,  203,  155,
      193,  166,  165,  150,  157,  154,   77,   77,  158,   77,
       77,  207,  219,   77,   77,  188,   77,  194,  155,   77,

       77,   77,   77,   77,   77,  233,  222,  231,  203,  232,
      226,   77,   77,  150,  155,  234,  189,  222,  235,  192,
      205,  201,  197,  203,  205,  205,  227,  227,  155,  109,
       77,   77,  158,  109,   77,   77,  193,  150,   77,  193,
       77,   77,  113,  186,   77,   77,  185,  185,   77,  163,
       77,  229,   77,   77,   81,   75,  238,  128,  123,  239,
       77,  118,   77,   77,   48,  240,   47,   47,   47,   81,
       47,  219,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       68,   68,   47,   68,   76,   47,   76,   82,   47,   82,

       99,   47,   99,   99,   47,   99,   99,   99,   99,  100,
       47,  100,  100,  100,  100,  100,  100,  100,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  107,  107,   47,
      107,  107,  107,  107,  107,  107,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  120,  241,  241,  120,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  127,  241,  127,
      127,  127,  127,  127,  127,  127,   77,  241,   77,  132,
      241,  132,  132,  132,  132,  132,  132,  132,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  112,  241,  112,

      112,  112,  112,  112,  112,  112,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  155,  155,  241,  155,  155,
      155,  155,  155,  155,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  183,  183,  241,  183,  183,  183,  183,  183,  183,
      185,  185,  241,  185,  185,  185,  185,  185,  185,  186,
      186,  241,  186,  186,  186,  186,  186,  186,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  200,  200,  200,  200,

      200,  200,  200,  200,  200,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  206,  241,  206,  206,  206,  206,  206,
      206,  206,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  227,
      227,  227,  227,  227,  227,  227,  241,  227,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  237,  237,  237,  237,  237,

      237,  237,  237,  237,    5,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241
    } ;

static yyconst flex_int16_t yy_chk[954] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        7,    9,   12,   10,    9,   10,    3,    4,   16,   26,
      227,   18,   12,   16,   18,    7,   19,   10,   19,   26,
       21,   23,   21,   23,   23,   10,   13,   13,   21,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   20,   24,  226,   31,   24,   20,
       20,   25,   32,  221,   25,   25,   27,   31,   27,   27,
      220,   27,   32,   32,  219,   33,   34,   37,   35,   32,
       31,   27,   42,   36,   32,   33,   34,   37,   35,   46,
       33,   38,   37,   36,   46,   39,   34,   33,   35,   36,
       35,   38,   51,   40,   36,   39,   50,   52,   50,   52,
       59,  209,   42,   40,  208,  206,   53,   39,   53,   38,
       40,   54,   57,   54,   51,   63,   64,   63,   50,   52,

       53,   57,   76,   66,   64,   66,  100,   67,   53,   67,
       59,  100,   76,   54,   59,   67,   68,   69,   68,   69,
       69,   78,   69,   78,   80,   83,   80,   84,   85,  203,
      199,   86,   87,   88,   89,   83,  198,   84,   85,   85,
       83,   86,   87,   88,   89,   90,   91,   92,   87,  189,
       93,   84,   86,   94,   95,   90,   91,   92,   89,   88,
       93,   96,  169,   94,   95,  101,   97,   90,  110,   91,
      101,   96,   95,  111,  113,   93,   97,  156,   94,   96,
      103,  104,  103,  104,   97,  106,  114,  106,  114,  115,
      110,  115,  116,  128,  116,  111,  113,  117,  124,  117,

      114,  119,  103,  104,  125,  126,  124,  106,  114,  155,
      119,  115,  125,  126,  116,  128,  147,  134,  126,  117,
      129,  130,  129,  130,  131,  133,  131,  134,  129,  135,
      136,  137,  134,  138,  139,  133,  133,  140,  147,  135,
      136,  137,  137,  138,  139,  138,  141,  140,  140,  139,
      142,  143,  135,  144,  145,  136,  141,  148,  150,  146,
      142,  143,  159,  144,  145,  151,  127,  151,  145,  146,
      152,  153,  152,  153,  154,  171,  154,  143,  144,  146,
      150,  157,  168,  157,  159,  171,  160,  151,  160,  161,
      168,  161,  152,  153,  171,  162,  154,  162,  163,  164,

      163,  164,  170,  157,  170,  172,  173,  170,  174,  175,
      123,  161,  176,  177,  178,  172,  173,  162,  174,  175,
      163,  164,  176,  177,  178,  185,  174,  179,  180,  183,
      181,  183,  176,  182,  184,  175,  184,  179,  180,  178,
      181,  180,  186,  182,  186,  187,  192,  185,  182,  196,
      179,  183,  188,  190,  188,  190,  184,  191,  193,  191,
      193,  197,  204,  200,  186,  200,  205,  187,  192,  207,
      201,  196,  201,  122,  188,  190,  202,  210,  202,  191,
      193,  121,  120,  197,  204,  200,  211,  210,  205,  212,
      213,  207,  201,  214,  215,  218,  211,  218,  202,  212,

      213,  216,  217,  214,  215,  213,  222,  211,  222,  212,
      237,  216,  217,  112,  223,  215,  223,  224,  216,  224,
      225,  228,  225,  228,  229,  230,  229,  230,  222,  108,
      231,  233,  237,  107,  232,  234,  223,  105,  235,  224,
      231,  233,  225,  228,  232,  234,  229,  230,  235,  236,
      238,  236,  239,  240,   81,   75,  231,   65,   62,  232,
      238,   58,  239,  240,   48,  238,   47,   43,   41,   30,
       29,  236,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      244,  244,   28,  244,  245,   22,  245,  246,   17,  246,

      247,   15,  247,  247,   14,  247,  247,  247,  247,  248,
       11,  248,  248,  248,  248,  248,  248,  248,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  250,  250,    6,
      250,  250,  250,  250,  250,  250,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  253,    5,    0,  253,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  255,    0,  255,
      255,  255,  255,  255,  255,  255,  256,    0,  256,  257,
        0,  257,  257,  257,  257,  257,  257,  257,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  259,    0,  259,

      259,  259,  259,  259,  259,  259,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  261,  261,    0,  261,  261,
      261,  261,  261,  261,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  265,  265,    0,  265,  265,  265,  265,  265,  265,
      266,  266,    0,  266,  266,  266,  266,  266,  266,  267,
      267,    0,  267,  267,  267,  267,  267,  267,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  273,    0,  273,  273,  273,  273,  273,
      273,  273,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  277,
      277,  277,  277,  277,  277,  277,    0,  277,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"

#line 4 "scanner.l"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "1505063_symboltable.h"
int line_count=1;
SymbolTable* ob=new SymbolTable(7);
FILE *logout;
FILE *tokenout;

#line 778 "1505063.cpp"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 22 "scanner.l"

#line 999 "1505063.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 242 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 905 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "scanner.l"
BEGIN(comment);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "scanner.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "scanner.l"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 26 "scanner.l"
++line_count;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "scanner.l"
{
           fprintf(logout,"Line no %d: TOKEN <COMMENT> Lexeme %s found\n",line_count,yytext);
	         BEGIN INITIAL;
                }
	YY_BREAK
case YY_STATE_EOF(comment):
#line 31 "scanner.l"
{
	             fprintf(logout,"Line no %d: Unfinished comment  found\n",line_count);
                    printf("comment error");
					BEGIN INITIAL;
                 }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 36 "scanner.l"
{line_count++;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "scanner.l"
{
	
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 40 "scanner.l"
{
	                    int i,len=0;
	                    for(i=0;i<strlen(yytext);i++)
	                     {
                         if(yytext[i]=='\\')
		                len++;
	                    }
	fprintf(logout,"Line no %d: TOKEN <COMMENT> Lexeme %s found\n",line_count,yytext);
	line_count=line_count+len;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "scanner.l"
{
          fprintf(logout,"Line no %d: TOKEN <COMMENT> Lexeme %s found\n",line_count,yytext);
          }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 53 "scanner.l"
{
	int i,len=0;
	                    for(i=0;i<strlen(yytext);i++)
	                     {
                         if(yytext[i]=='\n')
		                len++;
	                    }
	                    fprintf(logout,"Line no %d: TOKEN <COMMENT> Lexeme %s found\n",line_count,yytext);
	                     line_count=line_count+len; 
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "scanner.l"
{
			fprintf(tokenout,"<IF>");
			fprintf(logout,"Line no %d: TOKEN <IF> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "scanner.l"
{
			fprintf(tokenout,"<ELSE>");
			fprintf(logout,"Line no %d: TOKEN <ELSE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "scanner.l"
{
			fprintf(tokenout,"<FOR>");
			fprintf(logout,"Line no %d: TOKEN <FOR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 77 "scanner.l"
{
			fprintf(tokenout,"<WHILE>");
			fprintf(logout,"Line no %d: TOKEN <WHILE> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "scanner.l"
{
			fprintf(tokenout,"<DO>");
			fprintf(logout,"Line no %d: TOKEN <DO> Lexeme %s found\n",line_count,yytext);
		}		
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "scanner.l"
{
			fprintf(tokenout,"<BREAK>");
			fprintf(logout,"Line no %d: TOKEN <BREAK> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "scanner.l"
{
			fprintf(tokenout,"<INT>");
			fprintf(logout,"Line no %d: TOKEN <INT> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "scanner.l"
{
			fprintf(tokenout,"<CHAR>");
			fprintf(logout,"Line no %d: TOKEN <CHAR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 97 "scanner.l"
{
			fprintf(tokenout,"<FLOAT>");
			fprintf(logout,"Line no %d: TOKEN <FLOAT> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "scanner.l"
{
			fprintf(tokenout,"<DOUBLE>");
			fprintf(logout,"Line no %d: TOKEN <DOUBLE> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 105 "scanner.l"
{
			fprintf(tokenout,"<VOID>");
			fprintf(logout,"Line no %d: TOKEN <VOID> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "scanner.l"
{
			fprintf(tokenout,"<RETURN>");
			fprintf(logout,"Line no %d: TOKEN <RETURN> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 113 "scanner.l"
{
			fprintf(tokenout,"<SWITCH>");
			fprintf(logout,"Line no %d: TOKEN <SWITCH> Lexeme %s found\n",line_count,yytext);
		}		
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 117 "scanner.l"
{
			fprintf(tokenout,"<CASE>");
			fprintf(logout,"Line no %d: TOKEN <CASE> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 121 "scanner.l"
{
			fprintf(tokenout,"<DEFAULT>");
			fprintf(logout,"Line no %d: TOKEN <DEFAULT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 125 "scanner.l"
{
			fprintf(tokenout,"<CONTINUE>");
			fprintf(logout,"Line no %d: TOKEN <CONTINUE> Lexeme %c found\n",line_count,yytext[0]);
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "scanner.l"
{
                          fprintf(logout,"Error at Line no %d: Ill formed %s found\n",line_count,yytext);
                  }
	YY_BREAK
case 28:
#line 133 "scanner.l"
case 29:
#line 134 "scanner.l"
case 30:
#line 135 "scanner.l"
case 31:
YY_RULE_SETUP
#line 135 "scanner.l"
{
	   //ob->InsertCurrent(yytext,"FLOAT");
	   //ob->PrintCurrent();
	        fprintf(tokenout,"<FLOATINGPOINT,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <FLOATINGPOINT,%s> Lexeme %s found\n",line_count,yytext,yytext);
        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 142 "scanner.l"
{
                          fprintf(logout,"Error at Line no %d: Too many Decimal point %s found\n",line_count,yytext);
                         }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 145 "scanner.l"
{
                  fprintf(logout,"Error at Line no %d: Invalid suffix %s found\n",line_count,yytext);
               }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 149 "scanner.l"
{
            fprintf(tokenout,"<CHARACTER,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <CHARACTER> Lexeme %s found\n",line_count,yytext);
       }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 154 "scanner.l"
{
                 fprintf(logout,"Error at Line no %d: Multicharacter constant  %s found\n",line_count,yytext);
            }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 157 "scanner.l"
{
	char c='\n';
	 fprintf(tokenout,"<CHARACTER,%c>",c);
			fprintf(logout,"Line no %d: TOKEN <CHARACTER> Lexeme %s found\n",line_count,yytext);

       }		
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 163 "scanner.l"
{
	char c='\t';
	 fprintf(tokenout,"<CHARACTER,%c>",c);
			fprintf(logout,"Line no %d: TOKEN <CHARACTER> Lexeme %s found\n",line_count,yytext);

       } 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "scanner.l"
{
	fprintf(logout,"Error at Line no %d: Unfinished Character %s found\n",line_count,yytext);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 173 "scanner.l"
{
	 fprintf(tokenout,"<LPAREN,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LPAREN,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 178 "scanner.l"
{
	 fprintf(tokenout,"<RPAREN,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RPAREN,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 183 "scanner.l"
{
	 fprintf(tokenout,"<LCURL,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LCURL,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 188 "scanner.l"
{
	 fprintf(tokenout,"<RCURL,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RCURL,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 193 "scanner.l"
{
	 fprintf(tokenout,"<LTHIRD,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LTHIRD,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 198 "scanner.l"
{
	 fprintf(tokenout,"<RTHIRD,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RTHIRD,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 203 "scanner.l"
{
	 fprintf(tokenout,"<COMMA,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <COMMA,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 208 "scanner.l"
{
	 fprintf(tokenout,"<SEMICOLON,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <SEMICOLON,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 213 "scanner.l"
{
	 fprintf(tokenout,"<INC,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <INC,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 218 "scanner.l"
{
	 fprintf(tokenout,"<DEC,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <DEC,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }
	YY_BREAK
case 49:
#line 224 "scanner.l"
case 50:
YY_RULE_SETUP
#line 225 "scanner.l"
{
			fprintf(tokenout,"<ADDOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <ADDOP> Lexeme %s found\n",line_count,yytext);
			//insert in symbol table and print symbol table content(only non empty buckets)
			// There is a '|' in "+"'s rule, this means match execute the action for following rule
		}
	YY_BREAK
case 51:
#line 232 "scanner.l"
case 52:
#line 233 "scanner.l"
case 53:
#line 234 "scanner.l"
case 54:
YY_RULE_SETUP
#line 234 "scanner.l"
{
		fprintf(tokenout,"<RELOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RELOP> Lexeme %s found\n",line_count,yytext);
        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 238 "scanner.l"
{
         fprintf(tokenout,"<RELOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RELOP> Lexeme %s found\n",line_count,yytext);
     }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 242 "scanner.l"
{
      fprintf(tokenout,"<RELOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RELOP> Lexeme %s found\n",line_count,yytext);
    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 246 "scanner.l"
{
      fprintf(tokenout,"<LOGICOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LOGICOP> Lexeme %s found\n",line_count,yytext);
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 250 "scanner.l"
{
      fprintf(tokenout,"<LOGICOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LOGICOP> Lexeme %s found\n",line_count,yytext);
    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 254 "scanner.l"
{
      fprintf(tokenout,"<ASSIGNOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <ASSIGNOP> Lexeme %s found\n",line_count,yytext);
    }
	YY_BREAK
case 60:
#line 259 "scanner.l"
case 61:
#line 260 "scanner.l"
case 62:
#line 261 "scanner.l"
case 63:
YY_RULE_SETUP
#line 261 "scanner.l"
{
        fprintf(tokenout,"<BITOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <BITOP> Lexeme %s found\n",line_count,yytext);
     }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 265 "scanner.l"
{
	    fprintf(tokenout,"<MULOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <MULOP> Lexeme %s found\n",line_count,yytext);

        }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 270 "scanner.l"
{
	 fprintf(tokenout,"<NOT,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <NOT,%s> Lexeme %s found\n",line_count,yytext,yytext);

     }		
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 275 "scanner.l"
{
				fprintf(tokenout,"<CONST_INT,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_INT> Lexeme %s found\n",line_count,yytext);
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 281 "scanner.l"
{
          fprintf(tokenout,"<STRING,%s>",yytext);
				fprintf(logout,"Line1 no %d: TOKEN <STRING> Lexeme %s found\n",line_count,yytext);
       }	
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 285 "scanner.l"
{
	                 printf("hello");
	                  char str[100];
					  char fstr[1000];
					  fstr[0]='\0';
					  int i=0;
					  int l=1;
					  int j=0;
					  for(i=0;l<strlen(yytext)-1;i++)
					  {
						 if((yytext[l]=='\\')&&(yytext[l+1]=='t'))
						 {
							 str[i]='\t';
							 
							 //printf("%c %c",yytext[l],str[i-1]);
							 l=l+2;
						 }
						  else if(yytext[l]=='\\')
						  {
							  str[i]='\0';
							  line_count++;
							l++;
							 // printf("%sdd",str);
							  strcat(fstr,str);
						   for(j=0;j<i;j++)
						   str[j]='\0';
						   i=-1;
						  }
						
						  else if(yytext[l]!='\n')
                          {str[i]=yytext[l];

                          // printf("%cf",str[i]);
						
                          			l++;			 
						   }
						   if(yytext[l]=='\n')
						   l++;
						  
						  
					  }
					  // printf("%s",str);
					   strcat(fstr,str);
					  printf("%s",fstr);
					   fprintf(tokenout,"<STRING,%s>",fstr);
				fprintf(logout,"Line no %d: TOKEN <STRING,%s> Lexeme %s found\n",line_count,fstr,fstr);
	                  }	
	YY_BREAK
case 69:
/* rule 69 can match eol */
#line 335 "scanner.l"
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 335 "scanner.l"
{
	fprintf(logout,"Error at Line no %d: Unfinished string %s found\n",line_count,yytext);
}	
	YY_BREAK
case 71:
#line 339 "scanner.l"
case 72:
YY_RULE_SETUP
#line 339 "scanner.l"
{
                 fprintf(tokenout,"<ID,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <ID> Lexeme %s found\n",line_count,yytext);
   }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 343 "scanner.l"
{
	fprintf(logout,"Line no %d: Unrecognized chracter\n",line_count);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 347 "scanner.l"
ECHO;
	YY_BREAK
#line 1640 "1505063.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 242 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 242 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 241);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 347 "scanner.l"



int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	logout= fopen("1505063_log.txt","w");
	tokenout= fopen("1505063_token.txt","w");

	yyin= fin;
	yylex();
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}

